name: Carga dos Eventos

on:
  schedule:
    - cron: '*/5 * * * *' 
  workflow_dispatch:

jobs:
  collect-and-load-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r extracao_carga/requirements.txt
        pip install db-dtypes                
        
    - name: Run data collection and loading script
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}        
        SERVER: ${{ secrets.SERVER }}
        DATABASE: ${{ secrets.DATABASE }}
        UID: ${{ secrets.UID }}
        PWD: ${{ secrets.PWD }}
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
        TABLE_ID: ${{ secrets.TABLE_ID }}
        TABLE_ID_PAR: ${{ secrets.TABLE_ID_PAR }}
        TABLE_ID_ALERTA: ${{ secrets.TABLE_ID_ALERTA }}
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}                     
      run: |
        python extracao_carga/status.py